=== minhaiqn96/CODE_GYM2/4. XML & JSON-20190809T101618Z-001/4. XML _ JSON/4. Examples/DOM/Employee_dtd.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Employee_dtd.dtd
    Author     : vincent
    Description: Purpose of the document follows.
-->

<!ELEMENT SalaryDetail (Employee+)>
<!ELEMENT Employee (EmployeeName, Grade,
           AccountNumber, Designation, PANNumber, PFNumber, Earning, Deduction)>
<!ATTLIST Employee
	EmployeeNumber ID #REQUIRED
>
<!ELEMENT EmployeeNumber (#PCDATA)>
<!ELEMENT EmployeeName (#PCDATA)>
<!ELEMENT Grade (#PCDATA)>
<!ELEMENT AccountNumber (#PCDATA)>
<!ELEMENT Designation (#PCDATA)>
<!ELEMENT PANNumber (#PCDATA)>
<!ELEMENT PFNumber (#PCDATA)>

<!ELEMENT Earning (Basic, HRA, CityAllowance, ConveyanceAllowance)>
   <!ELEMENT Basic (#PCDATA)>
   <!ELEMENT HRA (#PCDATA)>
   <!ELEMENT CityAllowance (#PCDATA)>
   <!ELEMENT ConveyanceAllowance (#PCDATA)>

<!ELEMENT Deduction (IncomeTax, PF, ProfessionalTax)>
   <!ELEMENT IncomeTax (#PCDATA)>
   <!ELEMENT PF (#PCDATA)>
   <!ELEMENT ProfessionalTax (#PCDATA)>

=== minhaiqn96/CODE_GYM2/4. XML & JSON-20190809T101618Z-001/4. XML _ JSON/4. Examples/DOM/Employees.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : Employees.xml
    Author     : vincent
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE SalaryDetail SYSTEM "Employee_dtd.dtd">
<SalaryDetail>
  <Employee EmployeeNumber="E01">
    <EmployeeName> Anna John </EmployeeName>
    <Grade> AMM1 </Grade>
    <AccountNumber> 3456995410 </AccountNumber>
    <Designation> Assistant Manager </Designation>
    <PANNumber> ABF00517D </PANNumber>
    <PFNumber> 66771122 </PFNumber>
    <Earning>
      <Basic> 12100 </Basic>
      <HRA> 4500 </HRA>
      <CityAllowance> 5000 </CityAllowance>
      <ConveyanceAllowance> 4000 </ConveyanceAllowance>
    </Earning>
    <Deduction>
      <IncomeTax> 1500 </IncomeTax>
      <PF> 3500 </PF>
      <ProfessionalTax> 1000 </ProfessionalTax>
    </Deduction>
  </Employee>
</SalaryDetail>
